apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-gbpj
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-gbpj
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-gbpj
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-gbpj
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-gbpj
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-ieom-tenant/rhtap-demo-app/hacbs-test-project-gbpj@sha256:437e592092f68641aba96bf9bbf2e88ed3f03a9b4aa367071f048af84780a8fe
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
